#!/usr/bin/env bash

USER=$1
DOMAIN=$2

if [ ! "$USER" ]; then
    echo "Debe pasar un nombre de usuario como primer argumento"
    exit 1
fi

if [ ! "$DOMAIN" ]; then
    echo "Debe pasar un dominio como segundo argumento (netdata.example.com)"
    exit 1
fi

DIRNAME="./data/nginx/htpasswd"
FILENAME="$DIRNAME/$DOMAIN"

mkdir -p "$DIRNAME"

sudo sh -c "echo -n '$USER:' >> $FILENAME"
sudo sh -c "openssl passwd -apr1 >> $FILENAME"

docker-compose restart
